Default to negative number for position
This code works fine in Python 2 because None is less than all numbers:

```
>>> None < float('-inf')
True
```

However comparing None to a number isn't allowed in Python 3:

```
>>> None > 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

I think this should default to -1 because all the comparisons in this
method will have the same result.