Move functions outside of the Migration class
Attempting to run squashmigrations gives the following error:

ValueError: Could not find function remove_user_permission_for_moderator_group in molo.core.migrations.0051_remove_user_permission_for_moderator_group.
Please note that due to Python 2 limitations, you cannot serialize unbound method functions (e.g. a method declared and used in the same class body). Please move the function into the main module body to use migrations.
For more information, see https://docs.djangoproject.com/en/1.11/topics/migrations/#serializing-values

This is solved by moving the functions outside of the Migration class