Ensure article in is articles list
Sometimes this doesn't happen which will cause a template exception

  File "/usr/local/lib/python2.7/site-packages/molo/core/templatetags/core_tags.py", line 691, in get_next_article
    next_article = articles[articles.index(article) - 1]
ValueError: <ArticlePage: Я и представить не могла, что на такое способна...> is not in list